### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by ghost** [Wednesnight/lostengine#1]
```
$ gdb Debug/Launcher 
GNU gdb (Ubuntu/Linaro 7.3-0ubuntu2) 7.3-2011.08
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://bugs.launchpad.net/gdb-linaro/>...
Reading symbols from /home/jens/Private/Repositories/lostengine/source/scons/Debug/Launcher...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/jens/Private/Repositories/lostengine/source/scons/Debug/Launcher 
[Thread debugging using libthread_db enabled]

Program received signal SIGSEGV, Segmentation fault.
__pthread_mutex_lock (mutex=0x0) at pthread_mutex_lock.c:50
50  pthread_mutex_lock.c: No such file or directory.
    in pthread_mutex_lock.c
(gdb) thread apply all bt

Thread 1 (Thread 0x7ffff7fc2760 (LWP 551)):
#0  __pthread_mutex_lock (mutex=0x0) at pthread_mutex_lock.c:50
#1  0x00000000004166ec in tthread::mutex::lock() ()
#2  0x00000000004244d3 in lost::common::Logger::logMessage(eastl::basic_string<char, eastl::allocator> const&, eastl::basic_string<char, eastl::allocator> const&, eastl::basic_string<char, eastl::allocator> const&) ()
#3  0x000000000042943c in lost::event::initGlobalEventPool() ()
#4  0x0000000000424678 in tthread::call_once(void (*)(), int&) ()
#5  0x00000000004295c1 in lost::event::Pool::instance() ()
#6  0x0000000000424f25 in lost::event::EventDispatcher::EventDispatcher() ()
#7  0x00000000005d9743 in lost::application::Application::Application() ()
#8  0x00000000005d9689 in lost::application::Application::getInstance() ()
#9  0x00000000004073bc in lost::application::runTasklet(int, char**, lost::application::Tasklet*) ()
#10 0x000000000040718a in lost::application::runResourceTasklet(int, char**, eastl::basic_string<char, eastl::allocator> const&) ()
#11 0x00000000004069df in main ()
```

**Comment by ghost** [comment]
Fixed in a32a275
