### ISSUE TITLE
Linux: segfault when closing the Launcher window

### ISSUE THREAD

**Issue by ghost** [Wednesnight/lostengine#5]
Close the launcher window via the (x) button (window decoration), and it crashes if any tasklets have been started and stopped:

```

Program received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x22a) at malloc.c:3709
3709    malloc.c: No such file or directory.
    in malloc.c
(gdb) thread apply all bt

Thread 1 (Thread 0x7ffff7fc2760 (LWP 21212)):
#0  __GI___libc_free (mem=0x22a) at malloc.c:3709
#1  0x00007ffff7151519 in XFree () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#2  0x0000000000417925 in lost::application::Application::finalize() ()
#3  0x00000000005d9be3 in lost::application::Application::~Application() ()
#4  0x00000000005dd6ca in std::tr1::_Sp_deleter<lost::application::Application>::operator()(lost::application::Application*) const ()
#5  0x00000000005dd1fb in std::tr1::_Sp_counted_base_impl<lost::application::Application*, std::tr1::_Sp_deleter<lost::application::Application>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() ()
#6  0x0000000000407dc6 in std::tr1::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#7  0x0000000000407c2d in std::tr1::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() ()
#8  0x0000000000407bd8 in std::tr1::__shared_ptr<lost::application::Application, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() ()
#9  0x0000000000407bf2 in std::tr1::shared_ptr<lost::application::Application>::~shared_ptr() ()
#10 0x00007ffff63ff821 in __run_exit_handlers (status=0, listp=0x7ffff675e5a8, run_list_atexit=true) at exit.c:78
#11 0x00007ffff63ff8a5 in __GI_exit (status=<optimized out>) at exit.c:100
#12 0x00007ffff63e5314 in __libc_start_main (main=0x406994 <main>, argc=1, ubp_av=0x7fffffffde28, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde18) at libc-start.c:258
#13 0x00000000004068d9 in _start ()
```

**Comment by ghost** [comment]
Same happens if you start the Launcher, start a tasklet, close the Launcher window, and then close the tasklet window.

**Comment by ghost** [comment]
Actually, the same happens whenever you close the last window it seems.

It might be worth noting that I've got tasklets in the launcher list, but none of them are running. Start launcher, stop launcher, crash.

**Comment by ghost** [comment]
Nope, even when I delete the preferences. It seems this is nicely reproducible at least.
